/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/about`; params?: Router.UnknownInputParams; } | { pathname: `/admin`; params?: Router.UnknownInputParams; } | { pathname: `/berita`; params?: Router.UnknownInputParams; } | { pathname: `/berita1`; params?: Router.UnknownInputParams; } | { pathname: `/berita2`; params?: Router.UnknownInputParams; } | { pathname: `/berita3`; params?: Router.UnknownInputParams; } | { pathname: `/berita4`; params?: Router.UnknownInputParams; } | { pathname: `/DataMasyarakat`; params?: Router.UnknownInputParams; } | { pathname: `/DataPengaduan`; params?: Router.UnknownInputParams; } | { pathname: `/DataPetugas`; params?: Router.UnknownInputParams; } | { pathname: `/FormPengaduan`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/kontak`; params?: Router.UnknownInputParams; } | { pathname: `/lacakpengaduan`; params?: Router.UnknownInputParams; } | { pathname: `/Navbar`; params?: Router.UnknownInputParams; } | { pathname: `/profil`; params?: Router.UnknownInputParams; } | { pathname: `/profiladmin`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/about`; params?: Router.UnknownOutputParams; } | { pathname: `/admin`; params?: Router.UnknownOutputParams; } | { pathname: `/berita`; params?: Router.UnknownOutputParams; } | { pathname: `/berita1`; params?: Router.UnknownOutputParams; } | { pathname: `/berita2`; params?: Router.UnknownOutputParams; } | { pathname: `/berita3`; params?: Router.UnknownOutputParams; } | { pathname: `/berita4`; params?: Router.UnknownOutputParams; } | { pathname: `/DataMasyarakat`; params?: Router.UnknownOutputParams; } | { pathname: `/DataPengaduan`; params?: Router.UnknownOutputParams; } | { pathname: `/DataPetugas`; params?: Router.UnknownOutputParams; } | { pathname: `/FormPengaduan`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/kontak`; params?: Router.UnknownOutputParams; } | { pathname: `/lacakpengaduan`; params?: Router.UnknownOutputParams; } | { pathname: `/Navbar`; params?: Router.UnknownOutputParams; } | { pathname: `/profil`; params?: Router.UnknownOutputParams; } | { pathname: `/profiladmin`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/about${`?${string}` | `#${string}` | ''}` | `/admin${`?${string}` | `#${string}` | ''}` | `/berita${`?${string}` | `#${string}` | ''}` | `/berita1${`?${string}` | `#${string}` | ''}` | `/berita2${`?${string}` | `#${string}` | ''}` | `/berita3${`?${string}` | `#${string}` | ''}` | `/berita4${`?${string}` | `#${string}` | ''}` | `/DataMasyarakat${`?${string}` | `#${string}` | ''}` | `/DataPengaduan${`?${string}` | `#${string}` | ''}` | `/DataPetugas${`?${string}` | `#${string}` | ''}` | `/FormPengaduan${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/kontak${`?${string}` | `#${string}` | ''}` | `/lacakpengaduan${`?${string}` | `#${string}` | ''}` | `/Navbar${`?${string}` | `#${string}` | ''}` | `/profil${`?${string}` | `#${string}` | ''}` | `/profiladmin${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/about`; params?: Router.UnknownInputParams; } | { pathname: `/admin`; params?: Router.UnknownInputParams; } | { pathname: `/berita`; params?: Router.UnknownInputParams; } | { pathname: `/berita1`; params?: Router.UnknownInputParams; } | { pathname: `/berita2`; params?: Router.UnknownInputParams; } | { pathname: `/berita3`; params?: Router.UnknownInputParams; } | { pathname: `/berita4`; params?: Router.UnknownInputParams; } | { pathname: `/DataMasyarakat`; params?: Router.UnknownInputParams; } | { pathname: `/DataPengaduan`; params?: Router.UnknownInputParams; } | { pathname: `/DataPetugas`; params?: Router.UnknownInputParams; } | { pathname: `/FormPengaduan`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/kontak`; params?: Router.UnknownInputParams; } | { pathname: `/lacakpengaduan`; params?: Router.UnknownInputParams; } | { pathname: `/Navbar`; params?: Router.UnknownInputParams; } | { pathname: `/profil`; params?: Router.UnknownInputParams; } | { pathname: `/profiladmin`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
    }
  }
}
